### ISSUE TITLE
CM ON CUM

### ISSUE THREAD

**Issue by ponez** [AHosseinRnj/SimpleVPN#2]
https://github.com/AHosseinRnj/SimpleVPN/blob/e0b79b89bf7887462f5cafa1cdb56b48ae752ead/Simple_VPN/Dashboard.cs#L51
This is wrong , this is pure fucking cancer i mean who uses Countries "Cm" Box? you should totally change it to CUM man 
here is some facts ABOUT CUM In Latin, a preposition meaning with, or a conjunction meaning when, because, or although:
From the Latin for "with", a term in many place names in England, e.g. Prestwich-cum-Oldham
cum tempore (with time); notation used at universities in German, Austrian, Swiss and Scandinavian countries for starting 15 minutes late
Referring to diplomas and degrees: cum laude (with praise), magna cum laude (with great praise); maxima cum laude (with maximal praise); summa cum laude (with highest praise); egregia cum laude (with outstanding praise)
"Cum", a song by Mykki Blanco from the 2012 EP Mykki Blanco & the Mutant Angels
"Cum", a song by Brooke Candy featuring Iggy Azalea from the album Sexorcism
A slang term for semen
Depending on the species, spermatozoa can fertilize ova externally or internally. In external fertilization, the spermatozoa fertilize the ova directly, outside of the female's sexual organs. Female fish, for example, spawn ova into their aquatic environment, where they are fertilized by the semen of the male fish.

During internal fertilization, however, fertilization occurs inside the female's sexual organs. Internal fertilization takes place after insemination of a female by a male through copulation. In most vertebrates, including amphibians, reptiles, birds and monotreme mammals, copulation is achieved through the physical mating of the cloaca of the male and female.In marsupial and placental mammals, copulation occurs through the vagina.

Approximately 200 million – 500 million spermatozoa (also called sperm or spermatozoans), produced in the testes, are released per ejaculation. If a man has undergone a vasectomy, he will have no sperm in the ejaculation.
In some pre-industrial societies, semen and other body fluids were revered because they were believed to be magical. Blood is an example of such a fluid, but semen was also widely believed to be of supernatural origin and effect and was, as a result, considered holy or sacred. The ancient Sumerians believed that semen was "a divine substance, endowed on humanity by Enki", the god of water The semen of a god was believed to have magical generative powers.49 In Sumerian mythology, when Enki's seed was planted in the ground, it caused the spontaneous growth of eight previously-nonexistent plants. Enki was believed to have created the Tigris and Euphrates rivers by masturbating and ejaculating into their empty riverbeds.32, 49 The Sumerians believed that rain was the semen of the sky-god An which fell from the heavens to inseminate his consort, the earth-goddess Ki,causing her to give birth to all the plants of the earth

Dew was once thought to be a sort of rain that fertilized the earth and, in time, became a metaphor for semen. The Bible employs the term "dew" in this sense in such verses as Song of Solomon 5:2 and Psalm 110:3, declaring, in the latter verse, for example, that the people should follow only a king who was virile enough to be full of the "dew" of youth.

The orchid's twin bulbs were thought to resemble the testicles, which is the etymology of the disease orchiditis. There was an ancient Roman belief that the flower sprang from the spilled semen of copulating satyrs.

In a number of mythologies around the world, semen is often considered analogous to breast milk. In the traditions of Bali, it is considered to be the returning or refunding of the milk of the mother in an alimentary metaphor. The wife feeds her husband who returns to her his semen, the milk of human kindness, as it were
Mucus – this is a slippery fluid that gives semen its jelly-like texture. It helps sperm to move through the man's urethra and inside the woman's vagina and cervix, and also stops them from spreading out too much from the semen when it is inside the woman's body.
Other substances such as galactose (another kind of sugar), pre-ejaculate and sialic acid.

**Comment by AHosseinRnj** [comment]
umm yea hmm, okay bro i'll think about it !

**Comment by ponez** [comment]
oh one thing i forgot to mention is 
"You may be surprised to learn how many people are seeking bigger loads of semen," reads the front page of biggerloads.com, a website dedicated to delivering on the promise offered in its URL. "People of all ages—both men and women—have their own reasons for wanting more male ejaculate."

Those reasons—more intense orgasms, makin' babies—are all pretty predictable. So too is the existence of a site like bigger loads. Over the years, we've seen an increasing preoccupation—due, perhaps, to the evolution and proliferation of cum-focused porn or supplement marketing—among men with the size, force, and consistency of their jizz.

It can be hard to know if the common advice you'll find floating around the internet is reliable. But doctors who study human ejaculate for fertility purposes and porn stars tasked with creating the biggest loads possible for visual effect have tons of insights on the dynamics of cum. And they seem to agree that there are a few means through which a man can "improve" his ejaculation, both in size and even taste.

For the latter, the blogosphere puts a lot of stock in the idea that eating certain foods like red meat or dairy, smoking, and drinking alcohol make your cum taste foul, while eating citrus and greens will make it taste sweeter. "If you are treating your body poorly, the last thing it cares about is producing high-quality cum!" says Johnny Sins, a performer active since 2006.

Sexologists like Carol Queen and some female porn performers have supported the idea that eating certain foods can help or hurt the taste of semen. Sins says female performers often complain that men who smoke have "chunky" cum. However, he doubts any single food will have a huge impact on semen's flavor, while other medical experts suspect you'd have to consume them in huge amounts to have any effect.

Additionally, there are a host of supplements with names like Sugar Cum and Sweeten 69 on the market that promise candy-quality jizz, with little to support those claims. (There are also gel strips that, likewise dubiously, claim to neutralize the taste of cum on the tongue.) But plain ol' pineapple juice seems to be the super fruit taster's choice for many self-professed sexperts. Still, Dr. Abraham Morgentaler believes, ultimately, we just haven't done enough study on what influences cum's taste, so most of this "is pure conjecture."

Morgentaler is the director of Men's Health Boston and an associate clinical professor of urology at Harvard Medical School, and points out why that kind of data is hard to come by. "You can imagine the difficulty of doing a study on that," he says. "Not only do you need the guys, but you need willing partners to actually taste it."

While there's no hard medical data on what might influence the taste of semen, Morgentaler acknowledges that he's heard anecdotes from patients about the effects of diet and disease, and says there's no reason to rule out the possibility that there could be some mechanism at work there. If there is an effect, though, it's probably not from consuming one or two super foods, but from a holistic shift to a healthy lifestyle. "If your partner doesn't like the way something tastes," says Morgentaler, "by all means, go ahead and experiment with dietary stuff, whether it's fruit juices or whatever."

To that point, several porn stars have told me over the years that teetotaling, non-smoking vegetarians and vegans have the most tasty (or tolerable) cum. And Sins believes his cum gets good reviews from the women he works with because of his overall healthy lifestyle. He doesn't smoke or do drugs, avoids drinking to excess, and maintains a diet rich in fruits and vegetables. He also drinks plenty of water.

Still, on the topic of taste, go in knowing this stuff is only anecdotal, and results may vary.

On the other hand, when it comes to size and force of ejaculate, medical science can offer some tangible evidence of improvements. Morgentaler says that alcohol consumption not only lowers sperm count, but also the amount of ejaculate. How turned on you are during sex has an effect on the size and force of a cumshot as well. Age often reduces force—and perhaps the amount of fluid—in an ejaculation as well. Sins supports this from practical experience.

But on one point, the two disagree slightly. Morgentaler says doctors have long known that sustained periods of abstinence between ejaculation leads to a stronger, larger dynamic. Sins thinks that varies case by case. "Everyone's different, but for me, 24 hours in between gives me the biggest, most powerful cumshots," he says. "You would think that the longer you wait the better it would be, but that isn't always true. After waiting a few days, I have a little more cum built up, but the power of the shot isn't as powerful as I'd like or expect. The cum just plops out, for lack of a better word."

Other things Sins has done in the past to improve the "power of the shot" and guard against the dreaded "plops" is take zinc supplements and ZMA,  which is popular among athletes and bodybuilders. Though both underwhelmed, "I could never really tell the difference," he says.

Point is, if you want a strong and forceful load, give your prostate a rest here and there—but maybe not too long. Don't look for supplements or quick fixes. Instead, just treat your body well, and accept that physical limitations like age might put a damper on your ambitions—although a few Kegel exercises might help too.

Lastly, it's also worth recognizing that no matter how much you try, you're probably never going to pop off a porn load. "Most of the 'cumshot' pictures you see… aren't cum," says Sins. "Producers use various types of lotions, soaps, etc. to mimic cum. Most go overboard and use large amounts, way more than any guy could physically cum."

Learn to love your load, even if it's just the average teaspoon worth. At least maybe now it'll taste better.
I winced watching this, because I am consumed with greedy but guilty desire when it comes to the issue of squirting inside the mouth and swallowing. I adore oral acceptance of my penile offering, but I'm cravenly apologetic asking for it, because I'm sure the texture and flavor are repulsive on my lover's palate. Fear of Samanthas also inhibits me: My crotch loves a tongue-lashing but my ego doesn't.

"I'm sorry, I'm sorry, please just spit it out anywhere, on me or the blankets; I'll clean it up and I'll bring you a big glass of cold water." Blow jobs bestowed on my happy organ invariably end with me mumbling ashamedly, as if I had just splattered eggnog all over the Christmas table. I view my gobs as disgusting dollops.

"You try it!" Samantha challenges her bewildered beau (Adam) when he bellows that she's acting like a squeamish princess. "If you're fine with it, I'll be fine with it." Adam initially resists sampling his spooge ("It's gay!" he whines), but eventually he chokes down his rancid cum, with an anguished expression on his defeated visage. Although he reports that he's "fine with it," we know that he's lying.

I lied too, 25 years ago, when I gobbled through the same horrible gastronomic gantlet. My lover Robyn perceived my bluff; she forced me to admit that I loathed the salty, viscous wad. Ever since then, my glee at getting my lollipop licked has been tainted with advance remorse: My receiver is about to be nauseous.

"Sex and the City" provided me with a glimmer of hope, though, a key to decontaminating the puddles of my prick. When Samantha presents her pungent dilemma at lunch to her female friends, they advise her that "it has something to do with nutrition ... there's something he could eat to make it sweeter." Her subsequent attempt to detox his dribblings with wheat grass juice and a ginger-melon smoothie proves unsuccessful, but I still wondered wistfully: Is a herbal remedy available? Is there a semen-sweetening savior?

I began my research by telephoning the busiest cocksucker I know: Trebor Healy, a gay poet who has praised slurping in paeans such as "Dick Prayer," "The Big Cock Candy Mountain" and "The Star-Spangled Boner." Trebor informed me that "organic vegetarians taste the best, and those who drink plenty of liquids put out a better consistency; the dehydrated lad can get a bit thick. Also, a man whose mouth tastes good will always have delicious cum, while a foul kiss leads to less-than-fabulous sperm."

Trebor's report depressed me, because I'm neither vegetarian nor an avid imbiber of beverages. My next call was even less reassuring. Al Lujan, a head-bobbing writer, performer and filmmaker, said that the first sperm he swallowed tasted the best because "it was dispensed from a 15-year-old kid who lived off candy. My following experiences left me with the impression that the older you get, the nastier your sperm tastes. Ah, sweet spurt of youth."

I'm 48 and I never eat sweets, so my phallus phlegm is getting fouler every day? I decided to stop querying gay guys immediately; my survey swiveled instead to wide-jawed women.

Ex-porn star Annie Sprinkle established her expertise on the topic when she modestly mentioned to me that she had "swallowed the cum of probably over 1,000 men." Her wholesome opinion -- "vegetarians have sweeter sperm than meat eaters" -- echoed Trebor's frightening analysis. Sprinkle also suggested that "smoking, drinking, drugs and asparagus negatively affect the flavor."

Sex surrogate Tara Livingston of Los Angeles received my next panicked call. Shrewdly, she stalled my self-disgust by conveying only the sperm taste enhancers: "plums, nectarines, oranges, lemons, limes, parsley, cilantro, spearmint, peppermint, grapefruit and green tea." Unfortunately, I don't nibble on any of that sissy stuff.

Sex writer Katy Bell -- who says she has "slurped the milky way from California to New York to Mexico" -- ticked off three nutritional tips for a mellow ejaculate: hard candies, gallons of apple juice and fruit. But her must-be-avoided list was far lengthier, and it included all of my favorite foodstuffs: asparagus, chicken, garlic, onions and dairy products. Egads! My dream menu is an abomination.

A quick Yahoo search of "taste of semen" info sank me further into self-revulsion. Asparagus popped up incessantly on my screen like a sprouting forest of the slender green shafts; it's unanimously the worst culprit in causing stinky semen. This plagued me because I eat entire phalanxes of the delicious spears every week -- big, fat battering rams and skinny arrows; I slather them all with mayonnaise and cram them into my maw, even the stems.

Milk products also make cum chunks notoriously nasty because of the "high bacterial putrefaction level," asserts Sexuality.org. Other edibles that sexperts consistently label as bitter wad wreckers (and that I haven't already mentioned) are red meat, broccoli, cauliflower, Brussels sprouts, greasy food, spices, coffee and chocolate. Chemically processed liquor creates an extremely acidic taste, but naturally fermented beverages like sake and Rolling Rock or Honey Brown beer give spunk a sugary taste. Tobacco is also guaranteed to gross out one's goo.

What makes a man's emission yummy? Pineapple, claims Lexx.com. Kiwi fruit and celery, says a chat man who grabbed this advice from "Nina Hartley's Guide to Fellatio" video. Mangoes are admired, plus every other sweet fruit and tangy sprig that Livingston and Bell mentioned. I clicked through numerous Web sites, desperately cataloging the rumored do's and don'ts, until I suddenly thought: Where's the scientific process? Are there only silly urban myths to rely on? Who has done the clinical research that can establish irrefutable facts?

Urologists, I decided. I dialed some dick doctors. Dr. Lawrence Ross of the University of Illinois in Chicago shocked me by totally dismissing the entire notion that disparity in taste even exists! "In all healthy men," he contended, "seminal fluids are constant and similar because they all include precise components -- potassium, calcium, sodium, magnesium, phosphorus, etc. -- that maintain the very stable pH acidity that is needed to support the spermatozoa." In other words, a foul stench is exactly what the polliwogs want.

Dr. Robert Oates of the Boston Medical Center offered only a grudging acceptance of the flavor theories. "I wouldn't be surprised if substances like garlic and asparagus that come out in urine and sweat were also secreted in semen," he admitted. "But there's no definitive data on this. Medical research is done for crucial health reasons and this doesn't qualify." What!? He's obviously wrong: Our planet would be infinitely more peaceful if semen tasted like Snapple.

My final inquiry was to William Fitzgerald, Ph.D., of the Silicon Valley Relationship and Sexuality Center. "Bill" warmly and promptly delivered a huge load of info. Semen's metallic taste, he explained, is due to its zinc ingredient, and "diabetics tend to have a honey or cantaloupe taste, most likely due to the spilling over of excess sugars in the body." When amino acids in certain foods are broken down, he continued, it's possible that the resulting products end up in the semen. Asparagus' curse, for example, could be that "methionine is broken down and methyl mercaptan is produced ... with its awful odor." Nicotine and certain drugs can also "be deposited in genital organs like the epididymis and seminal vesicles."

OK. All right. I memorized all my notes. If anyone knows how to make his spunk scrumptious, it's me. All I have to do to get the tastiest tube on earth is to subsist eternally on the sap of 12 stupid items that bore me to death. I'd do it, I decided. But then, I felt a sudden pang of evil hunger, a repulsive yearning inside my gut for asparagus and mayonnaise with slabs of greasy, spicy beef and a giant glass of chocolate milk.

My cum will stink forever, I sighed. But so what? I have options. I can yank it out and spew on the sheets. I can continue my mortified apologizing. I can offer my lover a strawberry Life Saver to suck on to combat the upcoming stench. I can try to discharge on the back of her throat: no taste buds there. I can tell her I love her: Romance sweetens reality's putridness.

But give up my favorite foods? No way. Ain't gonna happen. I'll never stop swallowing asparagus, even if it means I'll never get swallowed.
